### ISSUE TITLE
Remove unnecessary dependencies？

### ISSUE THREAD

**Issue by ericsun95** [jiayuasu/geotools-wrapper#1]
Currently the dependencies also includes spark, jts and Sedona. Are those truly needed? It seems we can just keep geotools dependencies to make it lightweighted

**Comment by jiayuasu** [comment]
@ericsun95 Note that: spark, jts and sedona dependencies are marked as "provided". See https://github.com/jiayuasu/geotools-wrapper/blob/main/pom.xml#L36

This means that they are not included in the produced jar.

**Comment by ericsun95** [comment]
Yeah, we can also remove it as it's not needed for the wrapper jar? It doesn't have to be in those specific version. E.x spark 3.0.1, etc. Just little bit misleading.

**Comment by jiayuasu** [comment]
It is actually needed. I have a few simple test cases to verify that the jar has been successfully packaged: https://github.com/jiayuasu/geotools-wrapper/tree/main/src/test/java/org/datasyslab/geotools_wrapper

**Comment by ericsun95** [comment]
I see, it's scope is more close to test instead of provided. No big difference in this case, I am fine with it. Thanks for explaining.
